import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Plus, Save } from 'lucide-react';
import tutorService from '../services/tutorService';
import TutorLayout, { Button, EmptyState, ErrorState, Loading, PageHeader, StatusBadge } from '../components/TutorLayout';
import { formatDate, formatTime, getError } from '../components/tutorUtils';
import './TutorPages.css';

const resourceId = (item) => item?._id || item?.id;
const studentProfile = (student) => student.profile || student;

export function StudentsPage() {
  const [students, setStudents] = useState(null); const [error, setError] = useState(''); const navigate = useNavigate();
  useEffect(() => { tutorService.getStudents().then((res) => setStudents(res.data || [])).catch((err) => setError(getError(err, 'Unable to load students.'))); }, []);
  return <TutorLayout><PageHeader eyebrow="Tutor workspace" title="Students" description="Manage the learners assigned to you." action={<Button onClick={() => navigate('/tutor/students/new')}><Plus size={17}/>Add Student</Button>}/>{students === null ? <Loading label="Loading students..."/> : error ? <ErrorState message={error}/> : students.length === 0 ? <EmptyState title="No students yet" text="Add your first student to start managing their sessions." action={<Button onClick={() => navigate('/tutor/students/new')}><Plus size={17}/>Add Student</Button>}/> : <div className="data-list">{students.map((student) => { const profile = studentProfile(student); return <article className="data-row" key={resourceId(student)}><div><strong>{student.name}</strong><span>{profile.subject} · {profile.currentLevel}</span></div><div className="row-actions"><Link className="text-link" to={`/tutor/students/${resourceId(student)}`}>View Profile</Link><Link className="text-link" to={`/tutor/sessions/new?studentId=${resourceId(student)}`}>Schedule</Link></div></article>; })}</div>}</TutorLayout>;
}

export function AddStudentPage() {
  const navigate = useNavigate(); const [form, setForm] = useState({ name:'', email:'', password:'', subject:'', currentLevel:'', learningGoals:'', weakAreas:'' }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const submit = async (event) => { event.preventDefault(); setError(''); if (!form.name || !form.email || !form.password || !form.subject || !form.currentLevel || !form.learningGoals) { setError('Complete all required fields, including learning goals.'); return; } setSaving(true); try { const res = await tutorService.createStudent(form); navigate(`/tutor/students/${resourceId(res.data.student)}`, { state: { message: 'Student created successfully.' } }); } catch (err) { setError(getError(err, 'Unable to create student.')); } finally { setSaving(false); } };
  return <TutorLayout><PageHeader eyebrow="Students" title="Add Student" description="Create a student profile to start managing their learning sessions."/><form className="form-panel" onSubmit={submit}>{error && <div className="form-error">{error}</div>}<div className="form-grid">{[['name','Student Name','Enter student name'],['email','Email','student@example.com'],['password','Temporary Password','At least 6 characters'],['subject','Subject','Mathematics'],['currentLevel','Current Level','Grade 10']].map(([name,label,placeholder]) => <label key={name}>{label}<input name={name} type={name==='password'?'password':'text'} value={form[name]} onChange={update} placeholder={placeholder} required /></label>)}</div><label>Learning Goals<textarea name="learningGoals" value={form.learningGoals} onChange={update} placeholder="What does the student want to achieve?" required/></label><label>Weak Areas<textarea name="weakAreas" value={form.weakAreas} onChange={update} placeholder="Topics the student struggles with"/></label><Button disabled={saving}>{saving ? 'Creating Student...' : 'Create Student'}</Button></form></TutorLayout>;
}

function SessionRows({ sessions, onOpen }) { return <div className="session-list">{sessions.map((session) => <button className="session-row" key={resourceId(session)} onClick={() => onOpen(resourceId(session))}><div><strong>{session.topic}</strong><span>{session.studentId?.name || 'Student'}</span></div><div><span>{formatDate(session.scheduledAt)} · {formatTime(session.scheduledAt)}</span><StatusBadge status={session.status}/></div></button>)}</div>; }

export function SessionsPage() { const [sessions,setSessions]=useState(null); const [error,setError]=useState(''); const navigate=useNavigate(); useEffect(()=>{tutorService.getSessions().then(r=>setSessions(r.data||[])).catch(e=>setError(getError(e,'Unable to load sessions.')))},[]); return <TutorLayout><PageHeader eyebrow="Tutor workspace" title="Sessions" description="Track upcoming, active, and completed sessions." action={<Button onClick={()=>navigate('/tutor/sessions/new')}><Plus size={17}/>Schedule Session</Button>}/>{sessions===null?<Loading label="Loading sessions..."/>:error?<ErrorState message={error}/>:sessions.length===0?<EmptyState title="No sessions scheduled" text="Schedule a session with one of your students." action={<Button onClick={()=>navigate('/tutor/sessions/new')}>Schedule Session</Button>}/>:<SessionRows sessions={sessions} onOpen={(id)=>navigate(`/tutor/sessions/${id}`)}/>}</TutorLayout>; }

export function StudentProfilePage() { const {studentId}=useParams(); const [result,setResult]=useState(null); const [error,setError]=useState(''); const navigate=useNavigate(); useEffect(()=>{tutorService.getStudentById(studentId).then(r=>setResult(r.data)).catch(e=>setError(getError(e,'Student not found.')))},[studentId]); if(!result) return <TutorLayout>{error?<ErrorState message={error}/>:<Loading label="Loading student profile..."/>}</TutorLayout>; const {student,profile,sessions}=result; return <TutorLayout><Link className="back-link" to="/tutor/students"><ArrowLeft size={16}/>Back to Students</Link><PageHeader eyebrow="Student profile" title={student.name} description={`${profile?.subject || 'Student'} · ${profile?.currentLevel || ''}`} action={<Button onClick={()=>navigate(`/tutor/sessions/new?studentId=${studentId}`)}><Plus size={17}/>Schedule Session</Button>}/><section className="profile-grid"><div className="info-panel"><h2>Student Information</h2><dl><dt>Subject</dt><dd>{profile?.subject}</dd><dt>Current Level</dt><dd>{profile?.currentLevel}</dd><dt>Learning Goals</dt><dd>{profile?.learningGoals || 'Not provided'}</dd><dt>Weak Areas</dt><dd>{profile?.weakAreas || 'Not provided'}</dd></dl></div><div className="info-panel"><h2>Sessions</h2>{sessions.length?<SessionRows sessions={sessions} onOpen={(id)=>navigate(`/tutor/sessions/${id}`)}/>:<EmptyState title="No sessions yet" text="Schedule the first session with this student."/>}</div></section></TutorLayout>; }

export function ScheduleSessionPage() { const params=new URLSearchParams(window.location.search); const [students,setStudents]=useState(null); const [form,setForm]=useState({studentId:params.get('studentId')||'',scheduledAt:'',topic:''}); const [error,setError]=useState(''); const [saving,setSaving]=useState(false); const navigate=useNavigate(); useEffect(()=>{tutorService.getStudents().then(r=>setStudents(r.data||[])).catch(e=>setError(getError(e,'Unable to load students.')))},[]); const update=e=>setForm({...form,[e.target.name]:e.target.value}); const submit=async e=>{e.preventDefault();setError('');setSaving(true);try{const res=await tutorService.createSession({...form,scheduledAt:new Date(form.scheduledAt).toISOString()});navigate(`/tutor/sessions/${resourceId(res.data)}`)}catch(err){setError(err.response?.status===409?'This time slot is already booked. Please choose another time.':getError(err,'Unable to schedule session.'))}finally{setSaving(false)}}; return <TutorLayout><PageHeader eyebrow="Sessions" title="Schedule Session" description="Choose a student and set a focused time for your next lesson."/><form className="form-panel" onSubmit={submit}>{error&&<div className="form-error">{error}</div>}<label>Student<select name="studentId" value={form.studentId} onChange={update} required><option value="">Select student</option>{students?.map(s=><option key={resourceId(s)} value={resourceId(s)}>{s.name}</option>)}</select></label><div className="form-grid"><label>Date and time<input name="scheduledAt" type="datetime-local" value={form.scheduledAt} onChange={update} required/></label><label>Topic<input name="topic" value={form.topic} onChange={update} placeholder="Enter session topic" required/></label></div><Button disabled={saving}>{saving?'Scheduling...':'Schedule Session'}</Button></form></TutorLayout>; }

export function SessionDetailPage() { const {sessionId}=useParams(); const [session,setSession]=useState(null); const [error,setError]=useState(''); const [notes,setNotes]=useState(''); const [saving,setSaving]=useState(false); const navigate=useNavigate(); useEffect(()=>{tutorService.getSessionById(sessionId).then(r=>{setSession(r.data);setNotes(r.data.notes||'')}).catch(e=>setError(getError(e,'Session not found.')))},[sessionId]); if(!session)return <TutorLayout>{error?<ErrorState message={error}/>:<Loading label="Loading session..."/>}</TutorLayout>; const start=async()=>{try{const r=await tutorService.updateSessionStatus(sessionId,'in_progress');setSession(r.data)}catch(e){setError(getError(e,'Unable to start session.'))}}; const saveNotes=async()=>{setSaving(true);try{const r=await tutorService.updateSessionNotes(sessionId,notes);setSession(r.data)}catch(e){setError(getError(e,'Unable to save notes.'))}finally{setSaving(false)}}; const complete=async()=>{if(!window.confirm('Complete this session? Once completed, the session notes can no longer be edited.'))return;try{const r=await tutorService.updateSessionStatus(sessionId,'completed');setSession(r.data)}catch(e){setError(getError(e,'Unable to complete session.'))}}; return <TutorLayout><button className="back-link" onClick={()=>navigate(-1)}><ArrowLeft size={16}/>Back</button><PageHeader eyebrow="Session" title={session.topic} description={`${session.studentId?.name || 'Student'} · ${formatDate(session.scheduledAt)} at ${formatTime(session.scheduledAt)}`} action={<StatusBadge status={session.status}/>}/>{error&&<div className="form-error">{error}</div>}<div className="detail-panel"><h2>Session Notes</h2><textarea value={notes} onChange={e=>setNotes(e.target.value)} readOnly={session.status!=='in_progress'} placeholder={session.status==='scheduled'?'Notes become available when the session starts.':'Add notes about this session.'}/>{session.status==='scheduled'&&<Button onClick={start}>Start Session</Button>}{session.status==='in_progress'&&<div className="detail-actions"><Button variant="secondary" onClick={saveNotes} disabled={saving}><Save size={16}/>{saving?'Saving...':'Save Notes'}</Button><Button onClick={complete}>Complete Session</Button></div>}{session.status==='completed'&&<p className="read-only">Completed sessions are read-only.</p>}</div></TutorLayout>; }